#!/bin/sh

# suzu has trouble landing in the recovery for upgrade installation occasionally.
# Trigger another reboot from here.
if [ -f /cache/recovery/ubuntu_command ]; then
    sync
    reboot -f recovery
fi

echo 20 > /sys/fs/cgroup/schedtune/schedtune.boost
echo 1 > /sys/fs/cgroup/schedtune/schedtune.prefer_idle

exit 0
